name: duks-dev

services:
  server:
    environment:
      - DEBUG=true
    build:
      context: server/
      dockerfile: Dockerfile
    image: duks-server-dev:latest
    volumes:
      - ./data/:/data:z
      - ./server/:/app:z
    ports:
      - 5000:5000
    stdin_open: true
    command: uv run python app.py
